### ISSUE TITLE
Automatic Reconciliation

### ISSUE THREAD

**Issue by rtluckie** [ricoberger/vault-secrets-operator#16]
If a secret is changed in vault, the change should be automatically reflected in the k8s secret. Reconciliation should be tune-able (e.g. every 600s)

It looks like this would be straight forward to implement for Vault K/V Version 2 by using the version.  For Vault K/V Version 1 you might consider adding a hash of the secret to an annotation in the k8s secret to facilitate reconciliation.

- For K/V Version 2:
   * If a specific version is defined in the VaultSecret then automatic reconciliation should be ignored
  * If no version is defined in the VaultSecret then the most recent version should be used reflected in the K8s secret

- For K/V Version 1:
   * If the secret changes in vault then it should be reflected in the k8s secret.

Also, it would be awesome if k8s secrets were deleted when/if the vault secrets were deleted and the vault secret value was verified in the k8s secret to prevent manual edits.

**Comment by rtluckie** [comment]
The work around I've been using is to delete the K8s secret after it has been updated in vault and let it be re-created.

**Comment by ricoberger** [comment]
Hi and thanks for your request. We are seeing this as issue to, because increasing the version in the CR seems a little bit annoying.

I will take a closer look. For now I only have one question: I think if no version is defined in the VaultSecret for a K/V Version 2 secret changes in vault should also be reflected in the k8s secret. This could be interpreted as use always the latest version. What do you think?

**Comment by rtluckie** [comment]
@ricoberger I could have phrased that better.  Sorry about that. :/ But yes, I would always use the latest version.

**Comment by ricoberger** [comment]
@rtluckie I added the logic for automatic reconciliation (PR #17), but I'm not sure about the following points:

1. **Delete the k8s secret, if the Vault secret was deleted:** If the Vault secret was deleted and "auto update" is enabled for the secret the reconciliation function would throw an error. In this case I think it would be the best to delete the k8s secret and disable the reconciliation. This would also stopping the reconciliation if the CR contains an invalid path. Currently I do not know what happens if the CR is updated (fix the invalid path). If the CR is reconciled again I would implement this solution, I would skip this.
2. **Prevent manual edits:** The only useful solution I see here, is to run the reconciliation for every Vault secret and always update the k8s secret with the values from Vault. I'm not sure if this is a good idea.

What do you think? Do you have a better idea?

**Comment by rtluckie** [comment]
@ricoberger I think I agree with you 100% on point (1).  On point (2) IMHO it is desirable to reconcile every vault secret at a reasonable interval 600s+.  This would ensure that vault is the single source of truth, would ensure uniform usage by operators and remove any doubt if a k8s secret's data is actually what is in vault.

**Comment by rtluckie** [comment]
@ricoberger thx for quick response.  I'll test ASAP.

**Comment by ecojan** [comment]
Hi @ricoberger 
Wanted to double check, if `autoreconciliation` is enabled and a Vault secret is deleted, the kubernetes secret is not deleted correct?
I would point out this should probably be covered in the documentation, to alleviate any concerns.

**Comment by ricoberger** [comment]
Hi @ecojan, when you delete a secret from Vault the secret in Kubernetes isn't deleted, but the operator will throw some errors that the secret can not be found in Vault anymore.

When you delete the CR `vaultsecrets.ricoberger.de` in your Kubernetes cluster, also the Kubernetes secret will be deleted.

**Comment by ecojan** [comment]
That was my understanding as well, wanted to double check 👍  thank you!
