### ISSUE TITLE
Is it possible to use GCP service accounts (using workload identity) to auth against vault?

### ISSUE THREAD

**Issue by prahaladramji** [ricoberger/vault-secrets-operator#55]
This is a question and not an issue.

I'm running vault-secrets-operator in GCP on multiple GKE clusters and vault only on one. With [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) one can map kubernetes service accounts to a GCP service account.

This would reduce the complexity of managing cluster hosts and service account tokens with vault as an out of band task. Instead if we can auth using GCP service account then there will not be a need to wrangle cluster credentials.

Let me know if this is something that's already possible to do?

Thank You.

**Comment by ricoberger** [comment]
Hi @prahaladramji, I'm not very familiar with GKE, but when I get it right this would require to support [Google Cloud Auth Method](https://www.vaultproject.io/docs/auth/gcp) in the operator?

I'm not sure if this will be implemented soon, since I'm currently not able to test this properly. If you have an idea for the implementation and want to come up with a PR, you are welcome.

**Comment by ricoberger** [comment]
This should be implemented by #132 now.
