### ISSUE TITLE
Errors: namespace not authorized

### ISSUE THREAD

**Issue by vinay2107** [ricoberger/vault-secrets-operator#70]
Hello, I recently upgraded my vault-secrets-operator to version `1.11.0` to test the new `vaultRole` field on the VaultSecret CR.
I get the below error by doing so. 
`2021-01-05T17:20:50.449Z	INFO	controllers.VaultSecret	Create client to get secret from Vault	{"vaultsecret": "mynamespace/testing-secret", "vaultRole": "myrole"}
2021-01-05T17:20:54.197Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "ricoberger.de", "reconcilerKind": "VaultSecret", "controller": "vaultsecret", "name": "testing-secret", "namespace": "mynamespace", "error": "Error making API request.\n\nURL: PUT https://vault-k8s.example.com:8200/v1/auth/test-eu/login\nCode: 500. Errors:\n\n* namespace not authorized"}`

note:
 1. My vault-secrets-operator configuration looks as below
`vault:
      address: "https://vault-k8s.example.com:8200"
      authMethod: kubernetes
      tokenPath: ""
      kubernetesPath: auth/test-eu
      kubernetesRole: ""
      reconciliationTime: 0
      namespaces: ""`

I kept the `kubernetesRole` value empty as per the updated documentation here https://github.com/ricoberger/vault-secrets-operator#using-specific-vault-role-for-secrets to skip the usage of the shared client. 

2. The vault role I am testing `myrole` is properly bound to the namespace `mynamespace` where I am trying to deploy my CR and expecting the k8s secret to turn up.

**Comment by ricoberger** [comment]
Hi @vinay2107, thanks for reporting. Your Vault role `myrole` must be bound to the service account for the operator. The default name of the service account is `vault-secrets-operator`. Can you check the configuration of your role in Vault please. It should look as follows:

![Bildschirmfoto 2021-01-05 um 19 10 09](https://user-images.githubusercontent.com/18552168/103682867-b9b9af80-4f89-11eb-8f75-2f156b3bb16e.png)

If this is looking correct can you try to use your role `myrole` as value for `kubernetesRole` in the Helm chart please. Then remove the the `vaultRole` field from your `testing-secret` VaultSecret.

**Comment by vinay2107** [comment]
Thanks for the quick reply @ricoberger

In my setup, 

The `vault-secrets-operator` is deployed in a different namespace ex: `mynamespace2` and `myrole` role is bound to `*` service account and `mynamespace` namespace. 

What I am trying to achieve here is that I want to deploy a single vault-secrets-operator instance in a namespace managed by me and then allow all my customers to deploy their `vaultSecrets` CRs in their namespaces and still be able to fetch the secrets to their own namespaces. 

The setup you re suggesting is what I had previously and everything worked well. But based on the readme’s from latest version, I was under the impression that you can put the value of `kuberenetesRole` empty and still be able to use a different role by specifying it on the CR.

**Comment by ricoberger** [comment]
Hi, I think this doesn't work this way. When the operator is deployed in the namespace `mynamespace2` then the Vault role `myrole` must be bound to the `vault-secrets-operator` service account in `mynamespace2`.

Then you can use `myrole` in every namespace. It is not possible to configure the operator that way, that a role can only be used in one namespace. For such a use case the operator must be deployed multiple times and then you can set the `vault. namespaces` field to the namespaces which should be watched by the operator.

Maybe the the following comment can help you https://github.com/ricoberger/vault-secrets-operator/issues/58#issuecomment-738928032

Yes the `kuberenetesRole` can be empty. I said that to check if the problem is within the implementation of the operator or the Vault role setup. If it works when the `kuberenetesRole` role is set, then there is a bug in the operator. If it also didn't work  when the `kuberenetesRole` is set to `myrole` the chances are high that the problem is within the configuration.

**Comment by ricoberger** [comment]
Hi @vinay2107, could you solve your problem?
