### ISSUE TITLE
Support for multiple vault namespaces

### ISSUE THREAD

**Issue by swarren83** [ricoberger/vault-secrets-operator#73]
I do not see where to set the vault namespace that secrets are pulled from.  Would it be possible to add vault_namespace to spec and use this in calls to execute [client.SetNamespace](https://github.com/hashicorp/vault/blob/master/api/client.go#L661)?

I have a use case where I have split my secrets across multiple vault namespaces to group them.  I would like to use a single role to access these secrets but need a way to set the correct vault namespace for each secret.

**Comment by ricoberger** [comment]
Hi @swarren83, we do not have a Vault Enterprise license, so I'm not 100 percent sure how this feature works. After a first look into the [documentation](https://www.vaultproject.io/docs/enterprise/namespaces#usage) it seems possible to specify the namespace within the path:

> For example, these three requests are equivalent:
> Path: `ns1/ns2/secret/foo`
> Path: `secret/foo`, Header: `X-Vault-Namespace: ns1/ns2/`
> Path: `ns2/secret/foo`, Header: `X-Vault-Namespace: ns1/`

My assumption would be, that it would already work, when the namespace is set as follows:

```yaml
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: foo
spec:
  path: ns1/ns2/secret/foo
  type: Opaque
```

Could you try this out? If this doesn't work, we can also add an additional `vaultNamespace` field to the CR, which is then used to set the `X-Vault-Namespace` header.

**Comment by swarren83** [comment]
That may work for kv1 but kv2 the path gets prefixed with "data".  That would turn `ns1/ns2/secret/foo` to `data/ns1/ns2/secret/foo` which is malformed.

**Comment by ricoberger** [comment]
Hi @swarren83, thanks for the clarification. I created #74 for this feature. Which adds a new field named `vaultNamespace` to the CR. The value from this field is then used to set the `X-Vault-Namespace` header right before the request to get the secret from Vault is executed.

Since we do not have a Vault Enterprise license, it would be very helpful, if you can test this feature, before we merge it to the master branch.

I can also push an image for the branch if needed.

**Comment by swarren83** [comment]
Yes, I would be happy to help with testing.  I am getting our environment setup to deploy vault-secrets-operator.  How long do you expect the change to take before it is ready for testing?

**Comment by ricoberger** [comment]
The PR should be ready for testing now. If I get it right, just the `X-Vault-Namespace` is needed.

You can use the following Docker image `ricoberger/vault-secrets-operator:dev` and CR `https://raw.githubusercontent.com/ricoberger/vault-secrets-operator/d20090095ad4ccb69663b19b6af5410a1d2d640d/config/crd/bases/ricoberger.de_vaultsecrets.yaml`. 

If you are using the Helm chart, you can also use this from the `add-support-for-vault-namespaces` branch.

**Comment by swarren83** [comment]
Thank you, I am getting our infrastructure configured to test this dev version.  I will update you if I have questions, comments, or the tests where successful.

**Comment by swarren83** [comment]
@ricoberger I need a way to set the namespace that vault uses during authentication.

`2021-02-02T15:18:01.039Z        ERROR   Could not create API client for Vault   {"error": "Put https://myvault.com:443/v1/auth/
kubernetes/login: dial tcp 1.2.3.4:443: connect: connection refused"}
`

This either needs the vault namespace appended to the URL or the `X-Vault-Namespace` header set with the value.  What do you think about adding `vault.authNamespace` to the helm configurables?

**Comment by ricoberger** [comment]
Thanks for testing it 🙂

I think we can add such value, but then the `vaultNamespace` field in the CR doesn't make much sense, because the operator is only able to operate in the namespace, which was set via this property, right?

One option could be to create a new client for each secret, when the `vaultNamespace` field is set (similar to how it is done for the Vault role https://github.com/ricoberger/vault-secrets-operator/blob/d20090095ad4ccb69663b19b6af5410a1d2d640d/controllers/vaultsecret_controller.go#L75). Then we can also have the `vaultNamespace` option in the Helm chart, which would be the "default" namespace.

The other option would to only set the namespace via the Helm chart. What do you think is the better option?

**Comment by swarren83** [comment]
I like updating the `vaultNamespace` for each client call.  In my use case, we auth to a root namespace and then switch to team namespaces to fetch secrets.

rootNamespace = my/root/ns
teamNamespace = team1

My auth call would set `X-Vault-Namespace` to `my/root/ns` and then get secret would set `X-Vault-Namspace` to `my/root/ns/team1`.  Does that make sense?

**Comment by ricoberger** [comment]
Makes sense. Would it also work if the auth call sets `X-Vault-Namespace` to `my/root/ns/team1` or is this not possible?

**Comment by swarren83** [comment]
Unfortunately, no that will not work.  The namespace has an auth module configured on it and when you set the namespace on the client it effectively switches namespaces and uses the configuration for the current namespace.

In my example, the rootNamespace has the auth configuration and the teamNamespace is simply used to group secrets and allow for access controls.
