### ISSUE TITLE
Inappropriate role binding created by helm chart when rbac.namespaced is true

### ISSUE THREAD

**Issue by acornax** [ricoberger/vault-secrets-operator#81]
We're trying to use vault-secrets-operator from within k8s namespaces.

Reading the values file indicated that we should be setting `rbac.namespaced` to `true`. See [here](https://github.com/ricoberger/vault-secrets-operator/blob/f9650e4d284f3ae18e74d41f4614770fc4b4f387/charts/vault-secrets-operator/values.yaml#L66)

Unfortunately, this causes vault-secrets-operators' chart to create a `RoleBinding` resource rather than a `ClusterRoleBinding` resource. See [here](https://github.com/ricoberger/vault-secrets-operator/blob/f9650e4d284f3ae18e74d41f4614770fc4b4f387/charts/vault-secrets-operator/templates/role-binding.yaml#L3). 

This is insufficient to allow vault to create a `TokenReview` resource, as `TokenReview` resources are not namespaced. Replacing the `RoleBinding` with a `ClusterRoleBinding` resolves the issue.

**Comment by acornax** [comment]
Unless I'm mistaken I think a `ClusterRoleBinding` should always be created. I'm happy to submit an MR.

**Comment by bartmeuris** [comment]
I added this `namespaced` config to allow a vault operator instance per namespace. This instance "namespaced" instance can then have limited access to a subset of the vault instance, with it's own ACL rules in Vault. For this reason, a `RoleBinding` is used, allowing the service account only access to the current namespace, instead of a global `ClusterRoleBinding`.

**Comment by acornax** [comment]
We are running a vault operator instance in each namespace as well. The issue we're having is that vault cannot create `TokenReview` resources when the service account JWT it is using only has a`RoleBinding`.

As I understand it, the reason for this is that `TokenReview` resources are not namespaced in kubernetes.

**Comment by ricoberger** [comment]
Hi @acornax, I didn't find the time to verify this, but after reading the following blog post https://wanwenli.com/kubernetes/2019/08/28/k8s-tokenreview-api-vault.html, I think you are right and we have to create a ClusterRoleBinding, which binds the `system:auth-delegator` ClusterRole to the ServiceAccount, when the Kubernetes authentication method is used.

I will check this out as soon as possible, but I think we can:

- Remove the `{{ include "vault-secrets-operator.kubernetesAuthRules" . | indent 2 }}` rules
- Use a `Role` instead of a `ClusterRole` for namespaced deployments
- Create an additional ClusterRole when the Kubernetes auth method is used, which binds the `system:auth-delegator` ClusterRole to the ServiceAccount of the operator

@bartmeuris are you using the Kubernetes auth method or token based authentication?

**Comment by bartmeuris** [comment]
> @bartmeuris are you using the Kubernetes auth method or token based authentication?

At the moment token-based, k8s based was limited to one cluster last time I checked, and I'm dealing with quite a few more (and only one vault instance)

**Comment by ricoberger** [comment]
Thanks @bartmeuris, thats it. The described problem is "only" relevant, when the operator uses the Kubernetes auth method.

I created an PR, which should fix the problem, by creating an additional ClusterRole and ClusterRoleBinding, when the Kubernetes auth method is used. This should allow namespaced deployments using the Kubernetes auth method now.

@acornax if you want, you can test #83, before we are merging this to master.

**Comment by acornax** [comment]
Thanks! I'll test it out tomorrow.

**Comment by acornax** [comment]
I just wanted to follow up and confirm everything works on our end. Thanks so much for making this change!

**Comment by ricoberger** [comment]
Thanks for reporting and your feedback.
